trigger: none

pool: my-agent-pool

variables:
  # Replace with values from your Azure DevOps project
  organization: akash66sheoran
  project: my-project  # Adjust if project name differs from working directory
  itemID: 1  # Replace with the ID of your PBI  # Use a Personal Access Token with "vso.work" scope

steps:
- script: |

    sudo apt update && sudo apt install jq -y

    authHeaderValue=$(echo -n ":$(pat)" | base64)

    response=$(curl --header "Authorization: Basic $authHeaderValue" --location https://dev.azure.com/$(organization)/$(project)/_apis/wit/workitems/$(itemID)?%24expand=all&api-version=7.2-preview.3)

    fileName=$(echo $response | jq -r '.relations[0].attributes.name')
    attachmentURL=$(echo $response | jq -r '.relations[0].url')
    attachmentID=${url##*/}

    echo $attachmentID

    #curl -o $fileName --header "Authorization: Basic $authHeaderValue" --location https://dev.azure.com/$(organization)/$(project)/_apis/wit/attachments/$attachmentID?api-version=7.2-preview.3

    #ls -lrt
    
    #cat $fileName