trigger: none

pool: my-agent-pool

variables:
  # Replace with values from your Azure DevOps project
  organization: akash66sheoran
  project: my-project  # Adjust if project name differs from working directory
  item: 1  # Replace with the ID of your PBI
  pat: u2wbgnvtl3fu5ox3c66i4gpfgvlaeds4xbibrlysmut44nsazrba  # Use a Personal Access Token with "vso.work" scope

steps:
- script: |
    curl -o output.json https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/{item}?api-version=7.2-preview.3

    ls -lrt

    cat output.json