trigger: none

pool: my-agent-pool

variables:
  # Replace with values from your Azure DevOps project
  organization: akash66sheoran
  project: my-project  # Adjust if project name differs from working directory
  itemID: 1  # Replace with the ID of your PBI  # Use a Personal Access Token with "vso.work" scope

steps:
- script: |
    curl --header "Authorization: Basic $(pat)" https://dev.azure.com/$(organisation)/$(project)/_apis/wit/workitems/$(itemID)?api-version=7.2-preview.3
