trigger: none

pool: my-agent-poos

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'echo $(Agent.BuildDirectory)'
    
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'echo $(Build.BuildId)'