trigger: none

pool: my-agent-pool

variables:
  # Replace with values from your Azure DevOps project
  organization: akash66sheoran
  project: my-project  # Adjust if project name differs from working directory
  item: 1  # Replace with the ID of your PBI
  pat: u2wbgnvtl3fu5ox3c66i4gpfgvlaeds4xbibrlysmut44nsazrba  # Use a Personal Access Token with "vso.work" scope

steps:
- script: |
    curl -H "Authorization: Basic $(echo -n ":u2wbgnvtl3fu5ox3c66i4gpfgvlaeds4xbibrlysmut44nsazrba" | base64)" -o output.json https://dev.azure.com/akash66sheoran/my-project/_apis/wit/workitems/1?api-version=7.2-preview.3

    ls -lrt

    cat output.json