trigger: none

pool: my-agent-pool

variables:
  # Replace with values from your Azure DevOps project
  organizationUrl: https://dev.azure.com/akash66sheoran
  project: my-project  # Adjust if project name differs from working directory
  workItemId: 1  # Replace with the ID of your PBI
  pat: u2wbgnvtl3fu5ox3c66i4gpfgvlaeds4xbibrlysmut44nsazrba  # Use a Personal Access Token with "vso.work" scope

steps:
- script: |
    sudo apt update && sudo apt install jq -y
    # Download the attachment using the Work Item Tracking (WIT) API
    fileName=$(curl -sSL -u :$pat "$organizationUrl/_apis/wit/workitems/$workItemId/attachments?api-version=7.1-preview.3&download=false" | jq -r '.[].name')
    downloadUrl=$(curl -sSL -u :$pat "$organizationUrl/_apis/wit/workitems/$workItemId/attachments?fileName=$fileName&api-version=7.1-preview.3")

    # Check if a file was found
    if [[ -z "$downloadUrl" ]]; then
    echo "No attachment found for PBI $workItemId"
    exit 1
    fi

    # Download the file using wget
    wget -q -O "$fileName" "$downloadUrl"

    echo "Downloaded file: $fileName"